modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory (28 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Alexthw46/Ars-Elemental/issues" #optional

license="GNU Lesser General Public License v3.0"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="ars_elemental" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Ars Elemental" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/ars-elemental-elemental-spell-foci" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "ars_elemental_logo.png" #optional
# A text field displayed in the mod UI
credits = "Thanks to Bailey for Ars Nouveau API, Sammy; and elucent for code help" #optional
# A text field displayed in the mod UI
authors = "Alexthw" #optional
# The description text for the mod (multi line!) (#mandatory)
description = '''
This Ars Nouveau add-on is about the Elemental Schools. More spell foci and equips, powering up one of the elemental schools, as well as new glyphs and hidden combos.
'''
[[dependencies.ars_elemental]] #optional
# the modid of the dependency
modId = "forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory = true #mandatory
# The version range of the dependency
versionRange = "[47,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
[[dependencies.ars_elemental]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ars_elemental]]
modId = "ars_nouveau"
mandatory = true
versionRange = "[1.20.1-4.9.0,)"
ordering = "AFTER"
side = "BOTH"
